version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "popRefAPI"
    ports:
      - "4000:4000"
    restart: "always"
    volumes:
      - './app:node_modules'